# Generated by Django 6.0.4 on 2026-04-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, choices=[('available', 'شحن متوفر'), ('local', 'شحن جزئي'), ('not_available', 'شحن غير متوفر')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
